# Basic Nav2 parameters tuned for TurtleBot3 Burger
amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    scan_topic: "scan"

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.22
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      acc_lim_x: 1.0
      acc_lim_theta: 2.0
      obstacle_approach_dist: 0.5

bt_navigator:
  ros__parameters:
    use_sim_time: true

recoveries_server:
  ros__parameters:
    use_sim_time: true

amcl:
  ros__parameters:
    use_sim_time: true

# Global planner parameters
planner_server:
  ros__parameters:
    use_sim_time: true

# Costmap (global and local) minimal settings
global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    update_frequency: 1.0
    static_map: true

local_costmap:
  ros__parameters:
    use_sim_time: true
    plugin_names: ["obstacle_layer", "inflation_layer"]
    plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]

